// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/redis.usecases.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/redis.usecases.go -destination=internal/usecases/mocks/mock_redis_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisUseCase is a mock of RedisUseCase interface.
type MockRedisUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRedisUseCaseMockRecorder
	isgomock struct{}
}

// MockRedisUseCaseMockRecorder is the mock recorder for MockRedisUseCase.
type MockRedisUseCaseMockRecorder struct {
	mock *MockRedisUseCase
}

// NewMockRedisUseCase creates a new mock instance.
func NewMockRedisUseCase(ctrl *gomock.Controller) *MockRedisUseCase {
	mock := &MockRedisUseCase{ctrl: ctrl}
	mock.recorder = &MockRedisUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisUseCase) EXPECT() *MockRedisUseCaseMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRedisUseCase) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisUseCaseMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisUseCase)(nil).Get), key)
}

// Set mocks base method.
func (m *MockRedisUseCase) Set(key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisUseCaseMockRecorder) Set(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisUseCase)(nil).Set), key, value, ttl)
}
